apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subxid
    app.kubernetes.io/name: subxid-web
    app.kubernetes.io/instance: subxid-web
  name: subxid-web
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.subxidWeb.replicas }}
  selector:
    matchLabels:
      app: subxid
      app.kubernetes.io/name: subxid-web
      app.kubernetes.io/instance: subxid-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: subxid
        app.kubernetes.io/name: subxid-web
        app.kubernetes.io/instance: subxid-web
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan-subxid
    spec:
      containers:
      - image: {{ .Values.subxidWeb.image }}
        imagePullPolicy: Always
        name: subxid-web
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: subxid-storage
          readOnly: true
        ports: 
        - containerPort: {{ .Values.subxidWeb.port }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: subxid-storage
        persistentVolumeClaim:
          claimName: subxid-pvc
